/* ── Page-specific JS ── */

// Filter tips by category
function filterTips(cat, btn) {
  document.querySelectorAll('.filter-tab').forEach(function(b){ b.classList.remove('active'); });
  btn.classList.add('active');
  var visible = 0;
  document.querySelectorAll('.tip-item').forEach(function(item) {
    var show = (cat === 'all' || item.dataset.cat === cat);
    item.style.display = show ? '' : 'none';
    if (show) visible++;
  });
  var allCount = document.getElementById('cnt-all');
  if (allCount && cat === 'all') allCount.textContent = visible;
}

// Open tip modal with content
var tipContent = {
  'Dog Nutrition': '<h6>🥩 What to Feed Your Dog Daily</h6><p>A balanced dog diet should consist of <strong>high-quality commercial kibble</strong> as the primary food source, supplemented occasionally with cooked lean meat, vegetables like carrots and green beans, and cooked rice or sweet potato.</p><p><strong>Portion guide:</strong></p><ul><li>Small dogs (up to 5 kg): ½ to 1 cup of dry food per day</li><li>Medium dogs (5–20 kg): 1 to 2 cups per day</li><li>Large dogs (20 kg+): 2 to 4 cups per day</li></ul><p><strong>Foods to avoid:</strong> chocolate, grapes, raisins, onions, garlic, macadamia nuts, xylitol (found in sugar-free products), and cooked bones.</p><p>Always provide fresh, clean water. Feed adult dogs twice a day and puppies 3–4 times daily.</p>',
  'Cat Nutrition': '<h6>🐟 Feeding Your Cat Right</h6><p>Cats are <strong>obligate carnivores</strong> — they must eat animal protein to survive. Unlike dogs, cats cannot synthesize certain essential nutrients like taurine and arachidonic acid, so a cat-specific diet is critical.</p><p><strong>Wet vs Dry food:</strong> Wet food (canned) provides much-needed hydration and is closer to a cat\'s natural diet. Dry kibble is convenient and good for dental health. Many vets recommend a mix of both.</p><p><strong>Portion guide:</strong></p><ul><li>Adult cats: roughly 200–250 calories per day (check the packaging)</li><li>Kittens: feed 3–4 times daily with kitten-specific formula</li><li>Senior cats (7yr+): lower calorie food to prevent weight gain</li></ul><p><strong>Never feed cats:</strong> onions, garlic, grapes, chocolate, alcohol, raw fish in large amounts, or dog food as a primary diet.</p>',
  'Vaccination': '<h6>💉 Vaccination Schedule for Pets</h6><p><strong>For Dogs (Core Vaccines):</strong></p><ul><li>6–8 weeks: Distemper, Parvovirus</li><li>10–12 weeks: DHPP (Distemper, Hepatitis, Parvovirus, Parainfluenza)</li><li>16–18 weeks: DHPP booster + Rabies</li><li>12–16 months: DHPP + Rabies booster</li><li>Thereafter: Every 1–3 years depending on vaccine type</li></ul><p><strong>For Cats (Core Vaccines):</strong></p><ul><li>6–8 weeks: FVRCP (Feline Viral Rhinotracheitis, Calicivirus, Panleukopenia)</li><li>10–12 weeks: FVRCP booster</li><li>14–16 weeks: FVRCP booster + Rabies</li><li>Thereafter: Annual or every 3 years per vet advice</li></ul><p>Contact the <strong>Boac Animal Shelter</strong> or your nearest vet clinic in Marinduque for affordable vaccination services.</p>',
  'Dog Grooming': '<h6>🛁 Dog Bathing & Coat Care</h6><p>Proper grooming keeps your dog clean, comfortable, and healthy. Here\'s a complete routine:</p><ul><li><strong>Bathing:</strong> Every 4–6 weeks with pet-safe shampoo. Rinse thoroughly to prevent skin irritation.</li><li><strong>Brushing:</strong> Daily for long-haired breeds; weekly for short-haired dogs. This removes loose fur and prevents matting.</li><li><strong>Nail trimming:</strong> Every 3–4 weeks. If you hear clicking on the floor, it\'s time. Use proper pet nail clippers.</li><li><strong>Ear cleaning:</strong> Check weekly. Clean gently with a cotton ball and vet-approved ear cleaner — never insert anything into the ear canal.</li><li><strong>Teeth brushing:</strong> 2–3 times per week with pet toothpaste (never human toothpaste).</li></ul><p>In Marinduque\'s humid climate, pay extra attention to skin folds and paw pads to prevent fungal infections.</p>',
  'Cat Grooming': '<h6>✂️ Cat Grooming at Home</h6><p>While cats groom themselves, they benefit greatly from your help:</p><ul><li><strong>Brushing:</strong> Short-haired cats: once a week. Long-haired cats: daily to prevent painful mats and reduce hairballs.</li><li><strong>Claw trimming:</strong> Every 2–3 weeks. Use sharp cat nail clippers. Only clip the clear tip — avoid the pink "quick."</li><li><strong>Ear care:</strong> Check weekly for dark discharge, odor, or excessive scratching (signs of ear mites). Clean with a vet-approved solution.</li><li><strong>Eye care:</strong> Gently wipe discharge from corners with a damp cotton pad. Each eye gets its own pad.</li><li><strong>Dental care:</strong> Use cat-safe toothpaste and a finger brush 2–3x per week if possible.</li></ul><p>Make grooming a positive experience with treats and calm, short sessions — especially for rescue cats who may be nervous.</p>',
  'Dog Exercise': '<h6>🏃 Daily Exercise for Dogs in Marinduque</h6><p>Exercise requirements by breed size:</p><ul><li><strong>Small dogs (Shih Tzu, Dachshund):</strong> 20–30 minutes daily. Short walks + indoor play.</li><li><strong>Medium dogs (Aspin mix):</strong> 45–60 minutes daily. Brisk walks, fetch, free running.</li><li><strong>Large dogs (Labrador, Golden Retriever):</strong> 1–2 hours daily. Running, swimming, agility games.</li></ul><p><strong>Heat safety tips for Marinduque\'s climate:</strong></p><ul><li>Walk during early morning (before 8am) or late afternoon (after 5pm) to avoid peak heat</li><li>Bring water on all walks — dogs can overheat quickly</li><li>Avoid hot pavement — test it with your hand for 5 seconds. If it\'s too hot for you, it\'s too hot for their paws</li><li>Watch for signs of heat stroke: excessive panting, drooling, weakness, collapse</li></ul>',
  'Cat Exercise': '<h6>🎯 Keeping Indoor Cats Active</h6><p>Cats need 15–30 minutes of active play per day, ideally in two sessions. Here\'s how to keep them engaged:</p><ul><li><strong>Interactive toys:</strong> Feather wands, laser pointers, crinkle balls. Rotate toys weekly to prevent boredom.</li><li><strong>Puzzle feeders:</strong> Makes mealtime a mental workout. Easy to DIY with an empty egg carton and kibble.</li><li><strong>Cat trees & shelves:</strong> Cats love to climb and observe from height. A window perch with an outdoor view provides hours of stimulation.</li><li><strong>Paper bags & boxes:</strong> Free, beloved, and endlessly entertaining.</li><li><strong>Other pets:</strong> A second cat (properly introduced) can provide companionship and play stimulation.</li></ul><p>A 10-minute focused play session before bedtime helps cats burn energy and sleep through the night.</p>',
  'Dog Training': '<h6>🏆 Basic Dog Training at Home</h6><p>Start training as soon as your dog arrives. Consistency is everything.</p><p><strong>5 essential commands:</strong></p><ul><li><strong>Sit:</strong> Hold treat above nose, move back over head. As dog sits, say "Sit" and reward.</li><li><strong>Stay:</strong> Ask to sit, open palm toward dog, say "Stay," step back. Return and reward.</li><li><strong>Come:</strong> Crouch down, say "Come!" with excitement. Always reward — never call your dog to punish them.</li><li><strong>Leave it:</strong> Place treat on floor, cover with hand. When dog stops trying, reward with a different treat.</li><li><strong>Down:</strong> From sit, hold treat at nose, lower to floor. Dog follows into down position. Say "Down" and reward.</li></ul><p><strong>Golden rules:</strong> Keep sessions to 5–10 minutes. End on a success. Use praise + treats. Never punish — redirect instead. Aspins and mixed breeds respond especially well to positive reinforcement.</p>',
  'Cat Behavior': '<h6>💬 Understanding Cat Body Language</h6><ul><li><strong>Slow blink:</strong> "I trust you and feel safe." Blink slowly back to communicate affection.</li><li><strong>Tail straight up:</strong> Happy and confident greeting.</li><li><strong>Tail puffed:</strong> Frightened or agitated. Give space immediately.</li><li><strong>Ears forward:</strong> Curious and engaged.</li><li><strong>Ears flattened back:</strong> Scared, angry, or in pain — approach with caution.</li><li><strong>Slow kneading (making biscuits):</strong> Contentment — behavior from kittenhood nursing.</li><li><strong>Chirping at windows:</strong> Excitement at prey (birds, lizards). Normal predatory behavior.</li><li><strong>Showing belly:</strong> Sign of trust, but NOT always an invitation to pet. Many cats will swat if you do.</li><li><strong>Head bunting (headbutting you):</strong> Marking you as "theirs" — the highest compliment from a cat.</li></ul>',
  'Pet Safety': '<h6>🛡️ Pet-Proofing Your Home Checklist</h6><p><strong>Remove or secure:</strong></p><ul><li>Toxic plants: Lilies (deadly to cats), sago palm, oleander, philodendron, poinsettia</li><li>Electrical cords — cover with cord protectors or use bitter spray</li><li>Chemicals: cleaning products, pesticides, fertilizers — store in locked cabinets</li><li>Medications — even "pet-safe" human meds in wrong doses can be fatal</li><li>Small objects: coins, rubber bands, hair ties (swallowing hazard)</li><li>Trash cans — use bins with locking lids</li><li>Open toilets — can be drowning hazard for puppies and kittens</li></ul><p><strong>Set up a safe zone:</strong> A crate or pen with bedding, water, and toys gives your new pet a secure space to decompress during the adjustment period.</p>',
  'Parasite Prevention': '<h6>🦟 Flea, Tick & Parasite Prevention</h6><p>In Marinduque\'s tropical climate, parasites are a year-round concern.</p><p><strong>Signs of fleas:</strong> Excessive scratching, tiny dark specks (flea dirt) in fur, hair loss, pale gums (severe infestation).</p><p><strong>Prevention options:</strong></p><ul><li><strong>Spot-on treatments:</strong> Applied monthly to the back of the neck. Effective against fleas, ticks, and some mites.</li><li><strong>Oral preventives:</strong> Chewable tablets (e.g., NexGard, Bravecto) — ask your vet for availability locally.</li><li><strong>Flea collars:</strong> Affordable option but less effective than spot-on or oral treatments.</li><li><strong>Regular combing:</strong> Use a fine-tooth flea comb weekly, especially after outdoor time.</li></ul><p><strong>Treating the home:</strong> Wash all bedding in hot water, vacuum thoroughly (especially under furniture), and treat your home with a pet-safe spray. All pets in the household must be treated simultaneously.</p>',
  'ID & Safety': '<h6>📍 ID Tags, Microchips & Lost Pet Plans</h6><p><strong>ID Tags:</strong> Every pet should wear a collar with an ID tag including the pet\'s name and your phone number. Tags are immediately visible to anyone who finds your pet.</p><p><strong>Microchips:</strong> A rice-grain-sized chip implanted under the skin between the shoulder blades. It\'s permanent, painless, and scanned by vets and shelters to identify lost pets. Registration with a national database is required. Ask your local vet in Boac or Gasan about microchipping services.</p><p><strong>If your pet goes missing:</strong></p><ol><li>Search your immediate neighborhood immediately — most pets are found within 500m of home</li><li>Post on local Facebook groups and community chats</li><li>Contact all Marinduque shelters and vet clinics</li><li>Put out worn clothing with your scent near your home</li><li>Place food and water near your door at night</li><li>Post clear photos on Furever Home and local lost pet pages</li></ol>'
};

function openTip(topic) {
  var modal = new bootstrap.Modal(document.getElementById('tipModal'));
  document.getElementById('tipModalTitle').textContent = topic;
  document.getElementById('tipModalBody').innerHTML = tipContent[topic] || '<p>Detailed guide coming soon! Contact our team for more information.</p>';
  modal.show();
}

function subscribeNewsletter() {
  var input = document.querySelector('.newsletter-input');
  if (!input || !input.value.includes('@')) {
    if (typeof showToast === 'function') showToast('Please enter a valid email address.', 'error');
    else alert('Please enter a valid email address.');
    return;
  }
  if (typeof showToast === 'function') showToast('🎉 Subscribed! Watch your inbox for pet care tips.');
  else alert('Subscribed! Thank you.');
  input.value = '';
}

function showToast(message) {
  var toast = document.getElementById('toast');
  var msg = document.getElementById('toastMsg');
  if (!toast || !msg) return;
  msg.textContent = message;
  toast.classList.add('show');
  clearTimeout(toast._t);
  toast._t = setTimeout(function(){ toast.classList.remove('show'); }, 3200);
}